version: '3.6'
services:
  postgres:
    container_name: montreal_elixir-postgres
    environment:
      - POSTGRES_DB=omerlo_dev
      - POSTGRES_PASSWORD=development
    image: postgres:10.3
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
